# try:
#     x = 5 / 0
# except ZeroDivisionError as e:
#     # `e` is the exception object
#     print("Got a divide by zero! The exception was:", e)
#     # handle exceptional case
#     x = 0
# finally:
#     print("The END")
#     # it runs no matter what execute.


# while True:
#     try:
#         a = int(input(": "))
#     except ValueError as e:
#         print("Kindly enter a number")
#     except Exception as e:
#         print("Base Exception")
#         print(e)
#     finally:
#         print("END")


print('hello')
a = input('enter here: ')
print(a)
